version: "3.7"
services:
  db_paymybuddydockerapp:
    container_name: dbpaymybuddy
    image: mysql
    ports:
      - 3305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dbpaymybuddy
    volumes:
      - paymybuddySavedDataMySQL:/var/lib/mysql
      - ./db_docker:/docker-entrypoint-initdb.d
    deploy:
      replicas: 1
      
  paymybuddyapp:
    container_name: paymybuddyapp
    image: paymybuddyapp
    build:
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - db_paymybuddydockerapp
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db_paymybuddydockerapp:3306/dbpaymybuddy?allowPublicKeyRetrieval=true&useSSL=false'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    restart: always
    deploy:
      replicas: 1

volumes:
  paymybuddySavedDataMySQL:
